### PR TITLE
#3 [fix] login, signup and securityConfig

### LINKED ISSUE #3: login
login

### PR DESCRIPTION
**Pull request by GOH01**

### CODE REVIEW

File: src/main/java/com/sku_likelion/Moving_Cash_back/config/SecurityConfig.java [hunk 1]
```diff
@@ -59,10 +59,10 @@ public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Excepti
 //                        .accessDeniedHandler(accessDeniedHandler()) // 인증은 되었지만 권한이 없는 사용자가 접근시 403응답을 주는 로직
             )
                 .authorizeHttpRequests(auth -> auth // 엔드포인트별 접근 권한 설정
-                        .requestMatchers("/auth/**").permitAll() // 누구나 접근가능
+                        .requestMatchers("/auth/**","/user/signup", "/user/login", "/error").permitAll() // 누구나 접근 가능한 API 경로
                         .requestMatchers("/actuator/health").permitAll()
                         .requestMatchers("/v3/api-docs/**", "/swagger-ui/**", "/swagger-ui.html").permitAll()  //Swagger 문서관련 누구나 접근가능
-                        .requestMatchers(HttpMethod.OPTIONS, "/**").permitAll() // CORS preflight요청은 누구나 접근가능
+                        .requestMatchers(HttpMethod.OPTIONS, "/**").permitAll() // CORS preflight 요청은 누구나 접근가능
```
Comment (JuheeNoh123) [inline src/main/java/com/sku_likelion/Moving_Cash_back/config/SecurityConfig.java:65]: 굿

**Review by JuheeNoh123 — APPROVED** [review]
